services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TRANSPORT_TYPE=http
      - REPOSITORY_TYPE=postgres
      - DSN=postgres://postgres:postgres@db:5432/authdb?sslmode=disable
    depends_on:
      - db
    networks:
      - auth-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge